version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres111
      POSTGRES_DB: fa_service_db
    ports:
      - "5432:5432"
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data

  fastapi_app:
    image: dontworrybro/fastapi-audio-service:v1.0
    container_name: fastapi_audio_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres111@db:5432/fa_service_db
      SECRET_KEY: c036deb905f7fb20da093e26cdc63d4ad48be6c5ca2561abf086fd47e7054b4e
      YANDEX_CLIENT_ID: 0e1648c226ef45818fef83a9e17a7536
      YANDEX_CLIENT_SECRET: f0555d175cae48219500c79f2f010aad
      TOKEN_EXPIRE_HOURS: 1
      REFRESH_TOKEN_EXPIRE_DAYS: 7
    ports:
      - "8000:8000"
    #volumes:
    #  - .:/app
    command: ["python", "app/main.py"]

volumes:
  postgres_data:
    driver: local